# Generated by Django 3.0.5 on 2021-07-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210712_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=2, upload_to='myphotos'),
            preserve_default=False,
        ),
    ]
